# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site favicons & manifest icons
# 9. Site navigation
#theme: alembic-jekyll-theme
remote_theme: daviddarnes/alembic@main
# 1. Files excluded from Jekyll builds
exclude:
  - README.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - screenshot.png
  - LICENSE
  - CNAME
  - Gemfile
  - Gemfile.lock
  - alembic-jekyll-theme.gemspec
  # - .jekyll-cache

# 2. Installed Gems
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-commonmark
  - jekyll-include-cache
  - jemoji
  # - jekyll-remote-theme

# 3. Gem settings
paginate: 5 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page
jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
twitter:
  username: DavidDarnes # jekyll-seo-tag > Owners twitter username
author: DavidDarnes # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: David Darnes # jekyll-seo-tag > real name
  links: # jekyll-seo-tag > social aliases (sameAs)
    - https://twitter.com/DavidDarnes
    - https://www.facebook.com/daviddarnes
    - https://www.linkedin.com/in/daviddarnes
    - https://github.com/daviddarnes
# markdown: CommonMark # Markdown parse settings, CommonMark performs slightly better an others in build time
# commonmark:
# options: ["SMART", "FOOTNOTES"]
# extensions: ["strikethrough", "autolink", "table"]

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Asia/Bangkok # Timezone for blog posts and alike

# 5. Collections
collections:
  posts:
    title: Posts # Needed for Siteleaf
    output: true
    description: "My thoughts and ideas" # The post list page content
    feature_text: |
      Chào mừng bạn đã đặt chân đến thế giới của tui. Những điều tôi không thể nói, đã từng muốn nói rồi lại thôi hay những điều đã nói rồi. Tất cả sẽ có ở đây
    feature_image: "https://picsum.photos/2560/600?image=866"

# 6. Jekyll collections settings
defaults:
  - scope:
      path: ""
    values:
      image: "/assets/default-social-image.jpg" # Default image for sharing
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  - scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
lang: vi # Set the site language
title: "Manh Do" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/logos/logo.svg" # Site logo, also used in jekyll-seo-tag
description: "" # Site description and default description, also used in jekyll-seo-tag

url: "https://manhcntt21.github.io/" # Site url, also used in jekyll-seo-tag
# url: "http://localhost:4000/" # Site url, also used in jekyll-seo-tag
# baseurl: "http://localhost:4000/"

repo: "https://github.com/daviddarnes/alembic"
email: "dotruongmanh@gmail.com"
disqus: "https-manhcntt21-github-io" # Blog post comments, uncomment the option and set the site ID from your Disqus account
date_format: "%-d %B %Y" # Blog post date formatting using placeholder formatting
# google_analytics: ""
# google_analytics_anonymize_ip: ""
service_worker: false # Will turn off the service worker if set to false
short_name: "MANHITBKHN" # The web application short name, defaults to the site title
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference

# 8. Site favicons & manifest icons
favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
  16: "/assets/logos/logo@16px.png"
  32: "/assets/logos/logo@32px.png"
  96: "/assets/logos/logo@96px.png"
  120: "/assets/logos/logo@120px.png"
  144: "/assets/logos/logo@144px.png"
  180: "/assets/logos/logo@180px.png"
  512: "/assets/logos/logo@512px.png"
  1024: "/assets/logos/logo@1024px.png"

# 9. Site navigation
navigation_header:
  - title: About me
    url: /
  # - title: Elements
  #   url: /elements/
  - title: Blog
    url: /blog/
  - title: Categories
    url: /categories/
  - title: Search
    url: /search/
  # - title: Fork Alembic
  #   url: https://github.com/daviddarnes/alembic

navigation_footer:
  - title: Adopted Alembic Theme
    url: https://alembic.darn.es/

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  Twitter: https://twitter.com/DavidDarnes
  LinkedIn: https://www.linkedin.com/in/daviddarnes
  GitHub: https://github.com/daviddarnes
  link: https://darn.es
  RSS: /feed.xml

sharing_links: # Appear at the bottom of single blog posts, add as desired. The value can be 'true' or the desired button colour
  Twitter: "#0d94e7"
  facebook: "#3B5998"
  Email: true

# Load custom fonts from fonts.google.com etc
#
# TIP: Try to keep the number of urls as low to reduce the performance cost
#      If multiple fonts can be requested in a single url opt for this
fonts:
  preconnect_urls:
    # - https://fonts.gstatic.com
  font_urls:
    # - https://fonts.googleapis.com/css2?family=Roboto&display=swap
    #   - https://fonts.googleapis.com/css2?family=Be+Vietnam+Pro:wght@100;200;300&display=swap
    # - https://fonts.googleapis.com/css2?family=Merriweather:wght@400;700&display=swap
